export type NodeStatus = "loading" | "unread" | "understood" | "struggling"

export interface HighlightEntry {
    id: string
    text: string
    nodeId: string
}

export interface ContentNodeData {
    markdown_content: string
    filename: string
    page_count: number
    pdf_id?: string
}

export interface ChatMessage {
    role: "user" | "model"
    content: string
}

export interface AnswerNodeData {
    question: string
    highlighted_text: string
    answer: string
    isLoading: boolean
    isStreaming: boolean
    status: NodeStatus
    parentResponseText?: string
    isMinimized?: boolean
    isExpanding?: boolean
    chatHistory?: ChatMessage[]
    /** Which PDF page this node belongs to (1-based) */
    pageIndex?: number
    /** If true, this node is shown on every page regardless of pageIndex */
    isPinned?: boolean
    /** Which Gemini model produced the answer */
    modelUsed?: string
}

export interface UploadResponse {
    markdown_content: string
    raw_text: string
    filename: string
    page_count: number
    pdf_id?: string
}

export interface QuizQuestion {
    question: string
    question_type: 'short_answer' | 'mcq'
    options?: string[]        // exactly 4 items when question_type === 'mcq'
    correct_option?: number   // 0-based index of correct option for MCQ
}

export interface ValidateAnswerResponse {
    status: 'correct' | 'incorrect' | 'partial'
    explanation: string
    model_used?: string
}

export interface QuizNodeInput {
    highlighted_text: string
    question: string
    answer: string
    page_index?: number
}

export interface FlashcardNodeData {
    question: string
    answer: string
    isFlipped: boolean
    status: NodeStatus
    isMinimized?: boolean
    isExpanding?: boolean
    isPinned?: boolean
    /** Which PDF page this card belongs to (1-based) */
    pageIndex?: number
    isLoading: boolean
    /** Which Gemini model produced this flashcard */
    modelUsed?: string
}

export interface QuizQuestionNodeData {
    /** 1-based page index this quiz belongs to */
    pageIndex: number
    /** 1-based question number within the page quiz */
    questionNumber: number
    /** The question text generated by Gemini */
    question: string
    /** The student's typed answer (after submission) */
    userAnswer?: string
    /** Gemini's grading feedback (after submission) */
    feedback?: string
    /** True while the grade-answer API call is in flight */
    isGrading: boolean
    /** Follow-up chat history within this quiz node */
    chatHistory?: ChatMessage[]
    /** If true, appears on all pages */
    isPinned?: boolean
    /** Self-assessment status: 'understood' | 'struggling' | 'unread' */
    status?: NodeStatus
    /** If true, only the question header is shown */
    isMinimized?: boolean
    /** Which Gemini model produced the grading feedback */
    modelUsed?: string
}

// ─── Multi-canvas / Homepage types ───────────────────────────────────────────

/** Metadata for a single canvas entry stored in manifest.json */
export interface CanvasMeta {
    id: string
    title: string
    createdAt: string
    modifiedAt: string
    pdfFilename?: string
    pageCount?: number
    /** ID of the parent folder (null/undefined = root level) */
    parentFolderId?: string | null
}

/** Metadata for a folder entry stored in manifest.json */
export interface FolderMeta {
    id: string
    name: string
    /** ID of the parent folder (null/undefined = root level) */
    parentFolderId?: string | null
    createdAt: string
}

/** Root manifest stored in the local StudyCanvas folder */
export interface Manifest {
    version: number
    user: { name: string }
    canvases: CanvasMeta[]
    folders?: FolderMeta[]
}
