export type NodeStatus = "loading" | "unread" | "understood" | "struggling"

export interface HighlightEntry {
    id: string
    text: string
    nodeId: string
}

export interface ContentNodeData {
    markdown_content: string
    filename: string
    page_count: number
}

export interface ChatMessage {
    role: "user" | "model"
    content: string
}

export interface AnswerNodeData {
    question: string
    highlighted_text: string
    answer: string
    isLoading: boolean
    isStreaming: boolean
    status: NodeStatus
    parentResponseText?: string
    isMinimized?: boolean
    isExpanding?: boolean
    chatHistory?: ChatMessage[]
    /** Which PDF page this node belongs to (1-based) */
    pageIndex?: number
    /** If true, this node is shown on every page regardless of pageIndex */
    isPinned?: boolean
}

export interface UploadResponse {
    markdown_content: string
    raw_text: string
    filename: string
    page_count: number
}

export interface QuizQuestion {
    question: string
    question_type: 'short_answer' | 'mcq'
    options?: string[]        // exactly 4 items when question_type === 'mcq'
    correct_option?: number   // 0-based index of correct option for MCQ
}

export interface ValidateAnswerResponse {
    status: 'correct' | 'incorrect' | 'partial'
    explanation: string
}

export interface QuizNodeInput {
    highlighted_text: string
    question: string
    answer: string
}

export interface FlashcardNodeData {
    question: string
    answer: string
    isFlipped: boolean
    status: NodeStatus
    isMinimized?: boolean
    isExpanding?: boolean
    isPinned?: boolean
    /** Which PDF page this card belongs to (1-based) */
    pageIndex?: number
    isLoading: boolean
}

export interface QuizQuestionNodeData {
    /** 1-based page index this quiz belongs to */
    pageIndex: number
    /** 1-based question number within the page quiz */
    questionNumber: number
    /** The question text generated by Gemini */
    question: string
    /** The student's typed answer (after submission) */
    userAnswer?: string
    /** Gemini's grading feedback (after submission) */
    feedback?: string
    /** True while the grade-answer API call is in flight */
    isGrading: boolean
    /** Follow-up chat history within this quiz node */
    chatHistory?: ChatMessage[]
    /** If true, appears on all pages */
    isPinned?: boolean
    /** Self-assessment status: 'understood' | 'struggling' | 'unread' */
    status?: NodeStatus
    /** If true, only the question header is shown */
    isMinimized?: boolean
}
