export type NodeStatus = "loading" | "unread" | "understood" | "struggling"

export interface HighlightEntry {
    id: string
    text: string
    nodeId: string
}

export interface ContentNodeData {
    markdown_content: string
    filename: string
    page_count: number
    pdf_id?: string
}

export interface ChatMessage {
    role: "user" | "model"
    content: string
}

export interface AnswerNodeData {
    question: string
    highlighted_text: string
    answer: string
    isLoading: boolean
    isStreaming: boolean
    status: NodeStatus
    parentResponseText?: string
    isMinimized?: boolean
    isExpanding?: boolean
    chatHistory?: ChatMessage[]
    /** Which PDF page this node belongs to (1-based) */
    pageIndex?: number
    /** If true, this node is shown on every page regardless of pageIndex */
    isPinned?: boolean
    /** Which Gemini model produced the answer */
    modelUsed?: string
}

export interface UploadResponse {
    markdown_content: string
    raw_text: string
    filename: string
    page_count: number
    pdf_id?: string
}

export interface QuizQuestion {
    question: string
    question_type: 'short_answer' | 'mcq'
    options?: string[]        // exactly 4 items when question_type === 'mcq'
    correct_option?: number   // 0-based index of correct option for MCQ
}

export interface ValidateAnswerResponse {
    status: 'correct' | 'incorrect' | 'partial'
    explanation: string
    model_used?: string
}

export interface QuizNodeInput {
    highlighted_text: string
    question: string
    answer: string
    page_index?: number
}

export interface FlashcardNodeData {
    question: string
    answer: string
    isFlipped: boolean
    status: NodeStatus
    isMinimized?: boolean
    isExpanding?: boolean
    isPinned?: boolean
    /** Which PDF page this card belongs to (1-based) */
    pageIndex?: number
    isLoading: boolean
    /** Which Gemini model produced this flashcard */
    modelUsed?: string
}

export interface QuizQuestionNodeData {
    /** 1-based page index this quiz belongs to */
    pageIndex: number
    /** 1-based question number within the page quiz */
    questionNumber: number
    /** The question text generated by Gemini */
    question: string
    /** The student's typed answer (after submission) */
    userAnswer?: string
    /** Gemini's grading feedback (after submission) */
    feedback?: string
    /** True while the grade-answer API call is in flight */
    isGrading: boolean
    /** Follow-up chat history within this quiz node */
    chatHistory?: ChatMessage[]
    /** If true, appears on all pages */
    isPinned?: boolean
    /** Self-assessment status: 'understood' | 'struggling' | 'unread' */
    status?: NodeStatus
    /** If true, only the question header is shown */
    isMinimized?: boolean
    /** Which Gemini model produced the grading feedback */
    modelUsed?: string
}

// ─── Whiteboard / Drawing types ──────────────────────────────────────────────

export type WhiteboardTool = 'cursor' | 'pen1' | 'pen2' | 'highlighter' | 'eraser' | 'text'

export type EraserMode = 'stroke' | 'area'

export interface StrokePoint {
    x: number
    y: number
    pressure?: number
}

export interface DrawingStroke {
    id: string
    points: StrokePoint[]
    color: string
    width: number
    opacity: number
    tool: 'pen1' | 'pen2' | 'highlighter'
    pageIndex: number
    timestamp: number
    /** If set, points are node-relative (offset from node's top-left in flow coords) */
    nodeId?: string
    /** The node position when the stroke was created (fallback if node is deleted) */
    nodeOffset?: { x: number; y: number }
}

export interface PenSettings {
    color: string
    width: number
}

export interface HighlighterSettings {
    color: string
    width: number
    opacity: number
}

export interface EraserSettings {
    width: number
    mode: EraserMode
}

export interface TextToolSettings {
    fontSize: number
    color: string
}

export interface ToolSettings {
    pen1: PenSettings
    pen2: PenSettings
    highlighter: HighlighterSettings
    eraser: EraserSettings
    text: TextToolSettings
}

export interface TextNodeData {
    text: string
    fontSize: number
    color: string
    pageIndex: number
    isPinned?: boolean
    width?: number
    height?: number
}

export type WhiteboardUndoAction =
    | { type: 'addStroke'; stroke: DrawingStroke }
    | { type: 'removeStroke'; stroke: DrawingStroke }
    | { type: 'removeStrokes'; strokes: DrawingStroke[] }
    | { type: 'addText'; nodeId: string }
    | { type: 'removeText'; nodeId: string; nodeSnapshot: Record<string, unknown> }

export const DEFAULT_TOOL_SETTINGS: ToolSettings = {
    pen1: { color: '#000000', width: 3 },
    pen2: { color: '#2D9CDB', width: 3 },
    highlighter: { color: '#FFE066', width: 20, opacity: 0.4 },
    eraser: { width: 20, mode: 'stroke' },
    text: { fontSize: 16, color: '#000000' },
}

export const DEFAULT_SAVED_COLORS: string[] = [
    '#000000', '#FFFFFF', '#EB5757', '#2D9CDB',
    '#27AE60', '#FFE066', '#F2994A', '#9B51E0',
]

// ─── Multi-canvas / Homepage types ───────────────────────────────────────────

/** Metadata for a single canvas entry stored in manifest.json */
export interface CanvasMeta {
    id: string
    title: string
    createdAt: string
    modifiedAt: string
    pdfFilename?: string
    pageCount?: number
    /** ID of the parent folder (null/undefined = root level) */
    parentFolderId?: string | null
}

/** Metadata for a folder entry stored in manifest.json */
export interface FolderMeta {
    id: string
    name: string
    /** ID of the parent folder (null/undefined = root level) */
    parentFolderId?: string | null
    createdAt: string
}

/** Root manifest stored in the local StudyCanvas folder */
export interface Manifest {
    version: number
    user: { name: string }
    canvases: CanvasMeta[]
    folders?: FolderMeta[]
}
